#!/bin/bash

if [ $# -ne 2 ]; then
    echo 'invalid number of arguments.' >&2
    exit 1
fi

command=$1
name=$2


"$command" "./src/schemas/${name}.schemas.ts"
"$command" "./src/routes/${name}.routes.ts"
"$command" "./src/controllers/${name}.controllers.ts"
"$command" "./src/services/${name}.services.ts"
"$command" "./src/types/${name}.types.ts"